# Data Summary
## Drug Response
### Cell Line
#### CCLE
- Cells: 503
- Drugs: 24
- Pairs: 115660
#### CTRPV2
- Cells: 847
- Drugs: 461
- Pairs: 3109580
#### GCSI
- Cells: 571
- Drugs: 43
- Pairs: 132580
#### GDSCV1
- Cells: 984
- Drugs: 296
- Pairs: 2490150
#### GDSCV2
- Cells: 806
- Drugs: 169
- Pairs: 1139650
#### PRISM
- Cells: 478
- Drugs: 1418
- Pairs: 6386880
### Tumor
#### BEATAML
- Cells: 305
- Drugs: 108
- Pairs: 236620
#### MPNST
- Cells: 10
- Drugs: 25
- Pairs: 2640
#### NCI60
### Mixture
#### HCMI
## Cancer Cell
#### CPTAC
## Drug
#### FIMM
## Genome
#### MPNSTPDX

In [1]:
import coderdata as cd
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [2]:
data_name = 'ccle'
data_path = '../data/Cancer/coderdata/'
cd.download(name=data_name, local_path=data_path)
data = cd.load(name=data_name, local_path=data_path)

Downloaded 'https://ndownloader.figshare.com/files/51830555' to '../data/Cancer/coderdata/ccle_proteomics.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830558' to '../data/Cancer/coderdata/ccle_mutations.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830591' to '../data/Cancer/coderdata/ccle_copy_number.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830627' to '../data/Cancer/coderdata/ccle_experiments.tsv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830654' to '../data/Cancer/coderdata/ccle_transcriptomics.csv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830669' to '../data/Cancer/coderdata/ccle_drugs.tsv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51830726' to '../data/Cancer/coderdata/ccle_samples.csv'
Downloaded 'https://ndownloader.figshare.com/files/51830741' to '../data/Cancer/coderdata/ccle_drug_descriptors.tsv.gz'
Downloaded 'https://ndownloader.figshare.com/files/51966266' to '../data/Cancer/coderdata/genes.csv.gz'

Importing raw data ...
DONErting 'copy_number' from ../data/Cancer/coderdata/ccle_copy_number.csv.gz ...
DONErting 'mutations' from ../data/Cancer/coderdata/ccle_mutations.csv.gz ...
Importing 'genes' from ../data/Cancer/coderdata/genes.csv.gz ... DONE
DONErting 'proteomics' from ../data/Cancer/coderdata/ccle_proteomics.csv.gz ...
Importing 'drugs' from ../data/Cancer/coderdata/ccle_drugs.tsv.gz ... DONE
Importing 'drug_descriptors' from ../data/Cancer/coderdata/ccle_drug_descriptors.tsv.gz ... DONE
DONErting 'transcriptomics' from ../data/Cancer/coderdata/ccle_transcriptomics.csv.gz ...
Importing 'experiments' from ../data/Cancer/coderdata/ccle_experiments.tsv.gz ... DONE
Importing 'samples' from ../data/Cancer/coderdata/ccle_samples.csv ... DONE
Importing raw data ... DONE

In [3]:
data.drugs.to_csv("../data/Cancer/aggregation/ccle_drugs.csv", index=False)

In [8]:
import pandas as pd
data_megaMolBart_drugs = pd.read_csv("../data/Cancer/aggregation/ccle_megaMolBart_drugs.csv")
data_megaMolBart_drugs.head()

,improve_drug_id,chem_name,pubchem_id,canSMILES,InChIKey,formula,weight,megaMolBart_hidden,megaMolBart_padmsk,megaMolBart_embed
0,SMI_659,bp166224,5330286,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,AHJRHEGDXFFMBM-UHFFFAOYSA-N,C24H29N7O2,447.5,"tensor([[[-0.1887, 0.0842, 0.3640, ..., 0....","tensor([[True],\n [True],\n [Tru...","tensor([[-0.1880, 0.0835, 0.3628, ..., 0.3..."
1,SMI_659,nsc772256,5330286,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,AHJRHEGDXFFMBM-UHFFFAOYSA-N,C24H29N7O2,447.5,"tensor([[[-0.1880, 0.0835, 0.3628, ..., 0....","tensor([[True],\n [True],\n [Tru...","tensor([[-0.1880, 0.0835, 0.3628, ..., 0.3..."
2,SMI_659,dtxsid40972590,5330286,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,AHJRHEGDXFFMBM-UHFFFAOYSA-N,C24H29N7O2,447.5,"tensor([[[-0.1880, 0.0835, 0.3628, ..., 0....","tensor([[True],\n [True],\n [Tru...","tensor([[-0.1880, 0.0835, 0.3628, ..., 0.3..."
3,SMI_659,6-acetyl-8-cyclopentyl-5-methyl-2-((5-(piperaz...,5330286,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,AHJRHEGDXFFMBM-UHFFFAOYSA-N,C24H29N7O2,447.5,"tensor([[[-0.1880, 0.0835, 0.3628, ..., 0....","tensor([[True],\n [True],\n [Tru...","tensor([[-0.1880, 0.0835, 0.3628, ..., 0.3..."
4,SMI_659,otava-bb 1115529,5330286,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,AHJRHEGDXFFMBM-UHFFFAOYSA-N,C24H29N7O2,447.5,"tensor([[[-0.1880, 0.0835, 0.3628, ..., 0....","tensor([[True],\n [True],\n [Tru...","tensor([[-0.1880, 0.0835, 0.3628, ..., 0.3..."

In [10]:
# # Drug data processing
# import pandas as pd

# drugs_df = pd.read_csv("/opt/data/Cancer/aggregation/ccle_drugs.csv")
# drugs_df.head()
# smis = drugs_df["canSMILES"].tolist()
# hs_list = [] 
# pad_m_list = []
# emb_list = []

# for smi in smis:
#     hidden_states, pad_masks = connection.smis_to_hidden(smi)
#     hidden_states.shape, pad_masks.shape
#     hs_list.append(hidden_states.cpu())
#     pad_m_list.append(pad_masks.cpu())
#     embedding = connection.smis_to_embedding(smi)
#     embedding.shape
#     emb_list.append(embedding.cpu())
    
# drugs_df["megaMolBart_hidden"] = hs_list
# drugs_df["megaMolBart_padmsk"] = pad_m_list
# drugs_df["megaMolBart_embed"] = emb_list

# drugs_df.to_csv("/opt/data/Cancer/aggregation/ccle_megaMolBart_drugs.csv", index=False)

In [12]:
import os
print(os.getcwd())  # Prints the current working directory

/home/leo/Documents/DrugRes/src

In [13]:
data.types()

['transcriptomics',
 'proteomics',
 'mutations',
 'copy_number',
 'samples',
 'drugs',
 'experiments',
 'genes']

In [14]:
print(f"Cells: {len(data.experiments.improve_sample_id.unique().tolist())}\nDrugs: {len(data.experiments.improve_drug_id.unique().tolist())}\nPairs: {len(data.experiments)}")

Cells: 503
Drugs: 24
Pairs: 115660

In [15]:
data.experiments

,source,improve_sample_id,improve_drug_id,study,time,time_unit,dose_response_metric,dose_response_value
0,pharmacoGX,1.0,SMI_10282,CCLE,72,hours,fit_auc,0.9356
1,pharmacoGX,1.0,SMI_10376,CCLE,72,hours,fit_auc,0.8343
2,pharmacoGX,1.0,SMI_11509,CCLE,72,hours,fit_auc,0.6818
3,pharmacoGX,1.0,SMI_12635,CCLE,72,hours,fit_auc,0.6368
4,pharmacoGX,1.0,SMI_20869,CCLE,72,hours,fit_auc,0.7757
...,...,...,...,...,...,...,...,...
115655,pharmacoGX,1929.0,SMI_55576,CCLE,72,hours,dss,0.1964
115656,pharmacoGX,1929.0,SMI_55606,CCLE,72,hours,dss,0.0000
115657,pharmacoGX,1929.0,SMI_56571,CCLE,72,hours,dss,0.0000
115658,pharmacoGX,1929.0,SMI_659,CCLE,72,hours,dss,0.0000
115659,pharmacoGX,1929.0,SMI_7971,CCLE,72,hours,dss,0.0000

In [16]:
data.samples

,common_name,cancer_type,other_names,species,improve_sample_id,other_id_source,other_id,model_type
0,PK-59,Pancreatic Carcinoma,PK-59,Homo sapiens (Human),1,PatientID,PT-GiBvWu,cell line
1,PK-59,Pancreatic Carcinoma,PK-59,Homo sapiens (Human),1,DepMap,ACH-000205,cell line
2,PK-59,Pancreatic Carcinoma,PK-59,Homo sapiens (Human),1,Sanger,SIDM01774,cell line
3,PK-59,Pancreatic Carcinoma,PK-59,Homo sapiens (Human),1,CCLE,PK59_PANCREAS,cell line
4,PK-59,Pancreatic Carcinoma,PK-59,Homo sapiens (Human),1,Cellosaurus,CVCL_4897,cell line
...,...,...,...,...,...,...,...,...
13475,LU-99A,Giant Cell Carcinoma of the Lung,LU99A,Homo sapiens (Human),1744,DepMap,ACH-002158,cell line
13476,LU-99A,Giant Cell Carcinoma of the Lung,LU99A,Homo sapiens (Human),1744,Sanger,SIDM01219,cell line
13477,LU-99A,Giant Cell Carcinoma of the Lung,LU99A,Homo sapiens (Human),1744,CCLE,LU99A_LUNG,cell line
13478,LU-99A,Giant Cell Carcinoma of the Lung,LU99A,Homo sapiens (Human),1744,COSMIC,907796,cell line
13479,LU-99A,Giant Cell Carcinoma of the Lung,LU99A,Homo sapiens (Human),1744,Cellosaurus,CVCL_1393,cell line

In [17]:
data.transcriptomics

,entrez_id,improve_sample_id,transcriptomics,source,study
0,7105,137,4.331992,Broad,DepMap
1,64102,137,0.000000,Broad,DepMap
2,8813,137,7.364660,Broad,DepMap
3,6359,137,2.792855,Broad,DepMap
4,57147,137,2.792855,Broad,DepMap
...,...,...,...,...,...
18438731,100130705,1503,4.220000,Broad,Sanger & Broad Cell Lines RNASeq
18438732,100130705,1561,1.410000,Broad,Sanger & Broad Cell Lines RNASeq
18438733,100130705,1510,0.570000,Broad,Sanger & Broad Cell Lines RNASeq
18438734,100130705,1,8.570000,Broad,Sanger & Broad Cell Lines RNASeq
18438735,100130705,1558,1.520000,Broad,Sanger & Broad Cell Lines RNASeq

In [18]:
data.proteomics

         entrez_id  proteomics  improve_sample_id   study source
0             6558    2.111348                590  DepMap  Broad
1            23028    0.379683                590  DepMap  Broad
2             6657   -0.246367                590  DepMap  Broad
3             5396    0.322445                590  DepMap  Broad
4            51450   -0.246657                590  DepMap  Broad
...            ...         ...                ...     ...    ...
2461485      10945    0.276999                167  DepMap  Broad
2461486     153339   -0.951603                167  DepMap  Broad
2461487        241   -0.531699                167  DepMap  Broad
2461488      84418    0.964551                167  DepMap  Broad
2461489      29097    0.220199                167  DepMap  Broad

[2461490 rows x 5 columns]

In [19]:
data.copy_number

         entrez_id  improve_sample_id   copy_number copy_call source   study
0            79501                 31  3.880916e-08  deep del  Broad  DepMap
1            81099                 31  3.880916e-08  deep del  Broad  DepMap
2           729759                 31  1.417715e+00      gain  Broad  DepMap
3            81399                 31  1.417715e+00      gain  Broad  DepMap
4           148398                 31  1.417715e+00      gain  Broad  DepMap
...            ...                ...           ...       ...    ...     ...
9901060      55217                742  5.975769e-01  het loss  Broad  DepMap
9901061      10251                742  5.975769e-01  het loss  Broad  DepMap
9901062       6845                742  5.975769e-01  het loss  Broad  DepMap
9901063       3581                742  5.975769e-01  het loss  Broad  DepMap
9901064     548644                742  1.988455e+00       amp  Broad  DepMap

[9901065 rows x 6 columns]

In [20]:
data.mutations

,entrez_id,improve_sample_id,mutation,variant_classification,source,study
0,388581,1014,c.780_781GC>AG,Missense_Mutation,Broad,DepMap
1,54897,1014,c.3329T>C,Missense_Mutation,Broad,DepMap
2,54897,1014,c.3201A>C,Silent,Broad,DepMap
3,400736,1014,c.770C>T,Missense_Mutation,Broad,DepMap
4,391003,1014,c.653T>C,Missense_Mutation,Broad,DepMap
...,...,...,...,...,...,...
838642,8997,1322,c.5002G>T,Missense_Mutation,Broad,Sanger
838643,26038,1322,c.5002G>T,Missense_Mutation,Broad,Sanger
838644,84181,1322,c.5002G>T,Missense_Mutation,Broad,Sanger
838645,140625,1322,c.674T>G,Missense_Mutation,Broad,Sanger
838646,81669,1322,-,Intron,Broad,Sanger

In [21]:
data.mutations.variant_classification.unique().tolist()

['Missense_Mutation',
 'Silent',
 'In_Frame_Ins',
 'Splice_Site',
 'Nonsense_Mutation',
 'Frame_Shift_Del',
 'Nonstop_Mutation',
 'Start_Codon_SNP',
 'In_Frame_Del',
 'Frame_Shift_Ins',
 'Start_Codon_Ins',
 'Intron',
 "3'UTR",
 "5'Flank",
 "5'UTR",
 'Start_Codon_Del',
 'Translation_Start_Site',
 'Stop_Codon_Del']

In [22]:
data.genes

        entrez_id         other_id   gene_symbol     other_id_source
0               1              A1B          A1BG        entrez_alias
1               1              ABG          A1BG        entrez_alias
2               1              GAB          A1BG        entrez_alias
3               1         HYST2477          A1BG        entrez_alias
4               1             A1BG          A1BG        entrez_alias
...           ...              ...           ...                 ...
134505  131675794  ENST00000632371        NPIPA6  ensembl_transcript
134506  131675794  ENST00000620107        NPIPA6  ensembl_transcript
134507  131675794  ENST00000617392        NPIPA6  ensembl_transcript
134508  131768270  ENST00000715596  LOC131768270  ensembl_transcript
134509  131768270  ENST00000715679  LOC131768270  ensembl_transcript

[134510 rows x 4 columns]

In [23]:
data.drugs

,improve_drug_id,chem_name,pubchem_id,canSMILES,InChIKey,formula,weight
0,SMI_659,bp166224,5330286,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,AHJRHEGDXFFMBM-UHFFFAOYSA-N,C24H29N7O2,447.5
1,SMI_659,nsc772256,5330286,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,AHJRHEGDXFFMBM-UHFFFAOYSA-N,C24H29N7O2,447.5
2,SMI_659,dtxsid40972590,5330286,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,AHJRHEGDXFFMBM-UHFFFAOYSA-N,C24H29N7O2,447.5
3,SMI_659,6-acetyl-8-cyclopentyl-5-methyl-2-((5-(piperaz...,5330286,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,AHJRHEGDXFFMBM-UHFFFAOYSA-N,C24H29N7O2,447.5
4,SMI_659,otava-bb 1115529,5330286,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,AHJRHEGDXFFMBM-UHFFFAOYSA-N,C24H29N7O2,447.5
...,...,...,...,...,...,...,...
2504,SMI_56571,chembl1950720,11503417,CC(C(=O)NC(C1CCCCC1)C(=O)N2CCC3C2CN(CC3)CCC4=C...,HCSMRSHIIKPNAK-LSAVBLLPSA-N,C27H42N4O2,454.6
2505,SMI_56571,lbw242,11503417,CC(C(=O)NC(C1CCCCC1)C(=O)N2CCC3C2CN(CC3)CCC4=C...,HCSMRSHIIKPNAK-LSAVBLLPSA-N,C27H42N4O2,454.6
2506,SMI_56571,lbw-242,11503417,CC(C(=O)NC(C1CCCCC1)C(=O)N2CCC3C2CN(CC3)CCC4=C...,HCSMRSHIIKPNAK-LSAVBLLPSA-N,C27H42N4O2,454.6
2507,SMI_56571,"(2s)-n-[(1s)-2-[(3ar,7as)-6-(2-phenylethyl)-oc...",11503417,CC(C(=O)NC(C1CCCCC1)C(=O)N2CCC3C2CN(CC3)CCC4=C...,HCSMRSHIIKPNAK-LSAVBLLPSA-N,C27H42N4O2,454.6
2508,SMI_56571,"propanamide, n-((1s)-1-cyclohexyl-2-((3ar,7as)...",11503417,CC(C(=O)NC(C1CCCCC1)C(=O)N2CCC3C2CN(CC3)CCC4=C...,HCSMRSHIIKPNAK-LSAVBLLPSA-N,C27H42N4O2,454.6

In [24]:
data.format(data_type='transcriptomics')

entrez_id,1,2,9,10,12,13,14,15,16,18,...,115253422,116033993,118142757,118568804,122394733,122405565,124905743,125316803,127898561,128854680
improve_sample_id,,,,,,,,,,,,,,,,,,,,,
1,0.377908,0.214517,10.884808,1.004783,0.374231,5.125926,58.706594,0.178292,182.080289,4.410450,...,1.937344,0.0,0.128292,0.0,0.540773,2.314544,0.0,21.933752,10.997310,0.269329
4,0.068752,0.497908,14.466601,0.090195,0.329962,0.665773,89.898180,0.366517,119.751112,0.462088,...,2.513491,0.0,0.007178,0.0,1.978817,34.059067,0.0,31.096575,23.478747,0.000000
9,1.875525,0.307414,3.210817,0.000000,0.042032,0.048292,89.053021,0.075516,177.328384,0.102164,...,1.933573,0.0,0.000000,0.0,1.934707,45.165385,0.0,23.882962,34.018946,0.027178
10,0.055516,0.109517,3.116322,0.075000,0.215269,0.043292,52.793034,1.587481,48.576951,1.509450,...,2.589763,0.0,0.000000,0.0,2.093848,12.893512,0.0,28.347959,19.850747,0.261517
12,2.236951,0.118161,7.671384,0.000000,0.088161,0.000000,60.404582,0.852656,129.955312,4.494119,...,2.066950,0.0,0.015000,0.0,3.142531,1.096749,0.0,27.788301,30.176804,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1919,1.841711,0.083805,5.067848,0.000000,0.119393,0.000000,51.130153,3.460516,140.601954,0.731998,...,2.220330,0.0,0.042178,0.0,3.465080,0.953505,0.0,50.997643,42.976158,0.000000
1921,1.367750,60.166851,4.795926,1.116233,1.118805,2.972241,67.159499,0.567414,124.876073,20.823071,...,1.839960,0.0,0.000000,0.0,0.042032,28.611804,0.0,30.884286,34.351122,0.179517
1924,4.401903,0.137504,2.467279,0.000000,0.773996,0.084064,5.927659,1.049631,7.447001,1.655352,...,1.687061,0.0,0.000000,0.0,3.727920,1.220330,0.0,5.210233,5.020147,0.000000
1925,2.216196,0.233161,5.891079,0.000000,0.042032,0.000000,56.024912,0.454393,107.634286,3.782531,...,1.618239,0.0,0.000000,0.0,6.657481,8.408676,0.0,27.351329,24.425200,0.220280
1929,0.333424,0.124328,2.140779,1.257011,0.097611,0.124328,6.752347,0.214125,5.329124,4.441616,...,1.709291,0.0,0.014355,0.0,2.584963,3.232661,0.0,5.311430,4.408712,0.000000

In [25]:
data.format(data_type="copy_number", copy_call=True)

entrez_id,1,2,9,10,12,13,14,15,16,18,...,115253422,116033993,118142757,118568804,122394733,122405565,124905743,125316803,127898561,128854680
improve_sample_id,,,,,,,,,,,,,,,,,,,,,
1,amp,het loss,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,...,diploid,diploid,diploid,diploid,diploid,het loss,diploid,diploid,het loss,diploid
4,diploid,diploid,amp,amp,diploid,diploid,diploid,gain,diploid,diploid,...,diploid,diploid,diploid,diploid,het loss,diploid,amp,diploid,diploid,diploid
9,diploid,diploid,het loss,het loss,diploid,diploid,diploid,diploid,diploid,NaN,...,het loss,diploid,diploid,deep del,deep del,diploid,amp,het loss,diploid,gain
10,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,...,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid
12,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,...,gain,gain,diploid,diploid,het loss,diploid,gain,diploid,diploid,diploid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1919,diploid,diploid,diploid,diploid,diploid,gain,diploid,diploid,diploid,diploid,...,amp,diploid,diploid,diploid,het loss,diploid,gain,gain,diploid,diploid
1921,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,...,diploid,gain,diploid,diploid,deep del,diploid,gain,diploid,diploid,diploid
1924,diploid,het loss,het loss,het loss,diploid,diploid,diploid,diploid,diploid,diploid,...,diploid,gain,amp,diploid,het loss,diploid,diploid,diploid,diploid,diploid
1925,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,diploid,...,diploid,diploid,diploid,diploid,het loss,diploid,diploid,diploid,diploid,diploid
1929,diploid,diploid,deep del,deep del,diploid,diploid,diploid,diploid,diploid,gain,...,diploid,diploid,diploid,diploid,diploid,diploid,gain,diploid,diploid,diploid

In [26]:
data.format(data_type="copy_number", copy_call=False)

entrez_id,1,2,9,10,12,13,14,15,16,18,...,115253422,116033993,118142757,118568804,122394733,122405565,124905743,125316803,127898561,128854680
improve_sample_id,,,,,,,,,,,,,,,,,,,,,
1,1.422323,0.691416,1.153363,1.153363,1.140441,0.954812,0.931564,0.922500,0.961433,0.897050,...,1.118373,1.118373,0.935070,0.939545,1.072471,0.661407,0.740535,0.938108,0.672446,0.918687
4,1.009822,1.030186,1.615005,1.615005,0.984450,1.042251,1.031737,1.328189,1.001432,0.989615,...,1.028874,1.028874,1.025917,1.007712,0.613000,1.007189,1.765941,1.007712,0.994849,1.033792
9,0.930701,1.173626,0.714536,0.714536,0.958561,1.171976,0.981123,0.962056,0.952043,2.948380,...,0.726294,0.892899,0.963406,0.367068,0.413201,1.139820,1.637622,0.708532,1.148155,1.358754
10,1.015077,0.997647,0.985868,0.985868,0.993622,0.992827,0.981615,1.000990,1.000706,1.000706,...,0.996733,1.003704,0.998218,0.990853,0.939325,1.013123,1.005375,0.990853,1.005741,1.002318
12,0.995723,0.996596,0.989353,0.989353,0.995388,0.988751,0.991822,0.998354,0.996390,1.001431,...,1.301405,1.306209,0.990096,0.993266,0.581500,0.995037,1.388437,0.993266,0.995501,0.987063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1919,1.017744,0.985758,0.972158,0.972158,0.979758,1.284095,0.977705,0.991405,1.173671,0.986162,...,1.455214,1.191456,0.988807,0.989187,0.572521,0.997202,1.341251,1.305476,0.991108,0.974826
1921,1.028309,1.015692,0.783614,0.783614,0.785681,1.059697,1.069216,1.048842,0.777145,1.044846,...,1.041360,1.379463,1.077139,1.122806,0.457298,1.210156,1.293061,1.028766,1.050100,0.798262
1924,0.995641,0.603948,0.577524,0.577524,0.996201,0.989588,0.989758,0.990228,0.992690,0.994001,...,1.061903,1.303441,1.557160,0.994980,0.569774,0.995641,0.992730,0.990623,0.985878,0.986725
1925,1.012029,1.003935,0.996810,0.996810,1.002664,1.003684,1.000824,1.006239,1.006271,1.006911,...,1.008089,1.003146,1.004507,1.003966,0.594435,1.011999,1.008910,1.003966,0.999289,1.004416
1929,1.071931,1.108444,0.452828,0.452828,0.807115,1.194010,1.040468,1.046585,1.170474,1.264277,...,1.080735,1.048227,1.047615,1.001785,0.885882,0.802590,1.276910,1.009396,0.778092,0.893316

In [27]:
data.format(data_type='mutations', mutation_type="Silent")

entrez_id,1,2,9,10,12,14,15,16,18,19,...,110806280,110806290,111064647,111188157,112441426,112441434,112577516,112694756,113523638,116033993
improve_sample_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1919,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1921,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1924,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1925,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1929,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
data.format(data_type='mutations', mutation_type="Silent").columns

Index([        1,         2,         9,        10,        12,        14,
              15,        16,        18,        19,
       ...
       110806280, 110806290, 111064647, 111188157, 112441426, 112441434,
       112577516, 112694756, 113523638, 116033993],
      dtype='int64', name='entrez_id', length=16948)

In [29]:
data.format(data_type="proteomics")

entrez_id,2,9,12,14,16,18,19,20,21,22,...,102724560,105375355,105378803,106821730,110599583,110599588,112694756,122405565,125316803,127898561
improve_sample_id,,,,,,,,,,,,,,,,,,,,,
9,-0.806034,-0.382814,-1.278352,0.263905,0.069192,-0.723256,-0.264164,NaN,-0.132621,-0.385554,...,0.061427,NaN,NaN,NaN,-0.150745,0.116775,-0.521649,0.730529,-0.166007,NaN
10,-0.638222,NaN,NaN,-0.741678,-1.280059,2.301304,0.905719,NaN,NaN,0.156616,...,-2.832726,NaN,NaN,NaN,-0.970489,-0.979863,-0.987445,0.731932,-0.028343,-0.509149
16,3.905544,0.486126,NaN,0.651202,-0.061965,-1.154457,0.043314,1.228802,NaN,-0.668473,...,-0.649830,NaN,NaN,NaN,NaN,0.020253,0.178637,0.672807,-0.632077,-0.479577
25,-0.667066,NaN,NaN,-0.282675,-0.914788,-1.783631,0.207752,-0.528623,NaN,0.246502,...,-0.870346,NaN,NaN,NaN,-0.573028,0.099888,-0.610787,0.345912,0.380223,0.137098
29,-1.254556,-0.112991,-1.909443,-0.498685,-1.155756,-1.066216,-1.400999,-0.929177,0.692174,-0.645527,...,0.385313,-1.426838,-1.831299,1.836579,-0.041008,-0.469995,-0.335726,-0.460673,-0.059128,0.345387
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1907,0.438291,2.854572,NaN,-0.147775,-0.357613,-1.063209,-0.563127,NaN,NaN,-0.399018,...,-0.642544,NaN,NaN,NaN,-0.340436,-0.032841,1.008451,-1.932958,NaN,NaN
1908,-0.785533,1.196625,-0.890852,0.262247,-0.172732,2.219261,-0.515757,NaN,-0.107989,0.504114,...,-1.095232,NaN,NaN,-0.013294,NaN,-0.116022,-0.138931,-1.603167,0.427277,0.686355
1921,1.513325,0.099525,-0.326723,0.271783,-0.040915,2.002454,-0.094974,NaN,-0.206821,-0.355540,...,2.704777,NaN,NaN,NaN,0.743765,-0.168977,-0.676018,-0.069531,-0.128411,NaN
1924,-0.443011,0.253459,NaN,1.184467,1.428796,-0.232951,-0.160602,NaN,NaN,-0.714198,...,0.521077,NaN,-1.155299,NaN,1.145341,-0.028560,0.389555,-2.172993,-0.312964,0.075877
1929,-0.562606,0.027700,-1.031566,0.403108,-0.417326,1.257643,-1.327050,NaN,-0.863313,0.181252,...,-0.811144,NaN,NaN,-1.319040,NaN,0.561104,0.770857,-0.912318,-0.112624,-0.515547

In [30]:
data.format(data_type="experiments", shape="matrix", metrics="fit_auc")

improve_sample_id,1.0,4.0,9.0,10.0,12.0,14.0,16.0,17.0,25.0,27.0,...,1894.0,1901.0,1907.0,1908.0,1915.0,1919.0,1921.0,1924.0,1925.0,1929.0
improve_drug_id,,,,,,,,,,,,,,,,,,,,,
SMI_10282,0.9356,0.8844,0.7554,0.9719,0.8143,0.9129,0.8012,0.7120,0.9612,0.9623,...,0.8344,0.7266,0.7810,0.7836,0.9329,0.9838,0.8952,0.9789,0.8135,0.9715
SMI_10376,0.8343,0.7115,0.7354,0.9532,0.8801,0.9475,0.9624,0.7774,0.8774,0.6078,...,0.9167,0.7781,0.9678,0.9166,0.9257,0.8860,0.7907,0.8299,0.7426,0.9786
SMI_11509,0.6818,0.6990,0.5878,0.7798,0.7365,0.7697,0.6726,0.5781,0.7273,0.6846,...,0.7244,0.6514,0.7278,0.6363,0.6906,0.7723,0.6214,0.7005,0.7634,0.7321
SMI_12635,0.6368,0.4785,0.5343,0.5712,0.4551,0.5301,0.6021,0.5241,0.4830,0.6680,...,NaN,0.4904,0.5614,0.5424,0.5238,0.4597,0.7520,0.5146,NaN,0.6511
SMI_20869,0.7757,0.7485,0.7264,0.7578,0.9738,0.7336,0.7871,0.7184,0.7725,0.7528,...,0.7978,0.7193,0.8652,0.7735,0.7181,0.9978,0.7859,0.7541,0.7382,0.8033
SMI_24635,0.7420,0.7562,0.8212,0.7699,0.7791,0.8449,0.9741,0.7100,0.7227,0.7208,...,0.9264,0.7387,0.9031,0.7273,0.8502,0.7320,0.9168,0.7106,0.9727,0.7871
SMI_25849,0.6824,0.6060,0.6526,0.6141,0.7102,0.7035,0.7551,0.6774,0.6372,0.5916,...,0.7025,0.6392,0.7256,0.7430,0.6265,0.7248,0.7069,0.7297,0.7373,0.8152
SMI_33923,0.8127,0.7424,0.6711,0.7826,0.6637,0.8891,0.8237,0.7157,0.7587,0.7059,...,0.7476,0.6988,0.8720,0.7998,0.9573,0.9186,0.7577,0.7045,0.6571,0.8409
SMI_34999,0.7622,0.6681,0.5776,0.7329,0.6815,0.7951,0.7008,0.6880,0.7354,0.7386,...,0.7532,0.6475,0.7582,0.7708,0.7997,0.7031,0.6728,0.7132,0.7359,0.8240
SMI_35935,0.5852,0.5961,0.4532,0.4626,0.5582,0.5625,0.6493,0.4313,0.6571,0.5513,...,0.4044,0.4762,0.4714,0.5295,0.5941,0.6108,0.5527,0.6256,0.5401,NaN
SMI_39220,0.5726,0.3795,0.3918,0.3976,0.3653,0.3878,0.5216,0.3475,0.3282,0.4649,...,0.3000,0.3604,0.4429,0.4209,0.4486,0.3121,0.6194,0.2390,0.3320,0.5148
SMI_40153,0.7721,0.7448,0.7352,0.7773,0.8336,0.7527,0.9882,0.6755,0.7986,0.7551,...,NaN,0.7659,0.7886,0.9048,0.9628,0.9703,0.7340,0.7135,0.9404,0.8499
SMI_40233,0.5143,0.4712,0.4745,0.4781,0.3932,0.4896,0.5041,0.3940,0.4804,0.5401,...,0.4595,0.4616,0.4194,0.4336,0.3825,0.4627,0.4844,0.3751,0.5014,0.4776
SMI_42409,0.7613,0.7462,0.7458,0.8000,0.6577,0.8793,0.9362,0.8070,0.7744,0.7425,...,0.8440,0.9757,0.8581,0.8465,0.9889,0.9921,0.9597,0.6582,0.6512,0.8505
SMI_43543,0.6144,0.7369,0.6660,0.8249,0.9883,0.8422,0.7803,0.6638,0.7842,0.3965,...,0.8070,0.5715,0.4328,0.4929,0.5479,0.9852,0.6071,0.9184,0.5690,0.4627
SMI_46210,0.7387,0.8551,0.7094,0.8722,0.9694,0.8221,0.9055,0.7609,0.7565,0.5111,...,0.8248,0.6328,0.4984,0.5874,0.5827,0.9792,0.7172,0.9528,0.7401,0.5606
SMI_54714,0.7461,0.7338,0.7245,0.8787,0.7141,0.7930,0.8142,0.7019,0.7744,0.7297,...,0.7403,0.6911,0.7309,0.7414,0.7921,0.7249,0.7486,0.7240,0.8621,0.9238
SMI_5537,0.7278,0.9039,0.6753,0.9617,0.7810,0.7814,0.8513,0.6184,0.8126,0.6489,...,0.7278,0.7475,0.8851,0.6543,0.7700,0.8211,0.6964,0.7143,0.7489,0.7612
SMI_55576,0.6400,0.4563,0.5116,0.5751,0.4848,0.5497,0.6574,0.4784,0.5365,0.6430,...,0.5507,0.4982,0.5792,0.4910,0.5260,0.5201,0.8838,0.5116,0.5008,0.6767
SMI_55606,0.8773,0.7892,0.7029,0.9997,0.8173,0.9943,0.8361,0.7832,0.7263,0.9854,...,0.9598,0.7862,0.9916,0.8033,0.7989,0.8585,0.9430,0.9197,0.9674,0.9042
SMI_55652,0.7981,0.8232,0.7337,0.8603,0.9959,0.8006,0.8361,0.7103,0.8274,0.7544,...,0.8249,0.7298,0.9997,0.7805,0.7095,0.8759,0.9583,0.5959,0.8334,NaN
SMI_56571,0.8179,0.8703,0.9177,0.8696,0.9055,0.9006,0.8934,0.9620,0.9472,0.7804,...,0.9109,0.9220,0.9453,0.7817,0.8614,0.9507,0.9616,0.7475,0.7414,0.8170
SMI_659,0.8285,0.7276,0.7987,0.8962,0.7004,0.8784,0.8791,0.7627,0.8383,0.6894,...,NaN,0.8227,0.8181,0.7748,0.8992,0.7844,0.9857,0.7932,0.6982,0.9305
SMI_7971,0.9677,0.9653,0.7316,0.8389,0.7880,0.8116,0.8181,0.7122,0.8550,0.7346,...,0.8304,0.8553,0.7898,0.8128,0.7105,0.9037,0.8326,0.6915,0.8051,0.8905

In [31]:
len(data.format(data_type="drug_descriptor", shape="long").structural_descriptor.unique().tolist())

1614